// Generate `src/icons.js` - the button art, as base64 PNG, ready for a Companion `png64`.
//
//   node tools/icons/build-icons.mjs
//
// TWO RENDERS PER ICON, NOT ONE PER BUTTON COLOUR. The art is monochrome by rule, and the
// only ink that ever wins a contrast test is white or black, so white-on-transparent and
// black-on-transparent between them cover every background this module can be pointed at -
// including a row colour the table's owner has not chosen yet, and including the amber a
// `connection_lost` feedback paints over the top. The module picks at runtime with the same
// contrast test used here.
//
// The alternative - baking one PNG per row per surface - would have to be regenerated every
// time somebody edited a colour in the admin console, and nothing would say it was stale.

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { BLACK, WHITE, createCanvas } from './raster.mjs';
import { ICONS } from './icons.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, '..', '..', 'src', 'icons.js');
const SIZE = 72;

function render(draw, ink) {
  const c = createCanvas(SIZE);
  draw(c, { ink, size: SIZE });
  return c.toPng().toString('base64');
}

const names = Object.keys(ICONS);
const body = names
  .map((name) => {
    const light = render(ICONS[name], WHITE);
    const dark = render(ICONS[name], BLACK);
    return `\t'${name}': {\n\t\tlight:\n\t\t\t'${light}',\n\t\tdark:\n\t\t\t'${dark}',\n\t},`;
  })
  .join('\n');

const file = `// GENERATED by tools/icons/build-icons.mjs - do not edit by hand.
//
// Button art for the deck (#92), as base64 PNG for Companion's \`png64\`. Each icon ships
// twice: \`light\` is white ink for a dark button, \`dark\` is black ink for a light one. The
// module chooses between them by measuring contrast against the button's actual background,
// so art stays readable when the table's owner edits a row colour - and so the resting
// button and the lit button, which are different colours, each get the ink that reads on it.
//
// The shapes live in tools/icons/icons.mjs. Regenerate with:  npm run icons -w companion-module

export const ICONS = {
${body}
}
`;

writeFileSync(OUT, file);
console.log(`wrote ${OUT} - ${names.length} icons, ${(file.length / 1024).toFixed(1)} kB`);
