#!/usr/bin/env python3
"""
Generate configs/onair_assets.h from the files in assets/ (D-69).

WHY THIS EXISTS. On esp-idf there is no chunked response and no runtime compression, so a
dynamic page is one contiguous heap allocation sent raw. Inline CSS is therefore the most
expensive byte on the device - measured, 71% of GET /onair was its own <style> block, re-sent
and re-allocated on every request, on a board where a failed allocation is abort() and abort()
reboots the panel driving the light.

A flash blob costs none of that: AsyncWebServerResponseProgmem hands a const uint8_t* straight
to httpd_resp_send and copies nothing. So the assets are gzipped here, at build time, and the
handler serves them immutable-cached.

gzip, NOT brotli. Firefox refuses to decode Content-Encoding: br over plain HTTP and D-17 pins
this device to plain HTTP.

The header is COMMITTED, because `includes:` copies files verbatim and the build has no hook to
run this first. That means it can drift from its source, so `--check` exists and `npm run
verify` calls it. A stale header is a page that silently serves last week's stylesheet.
"""
import gzip
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent.parent
ASSETS = HERE / "assets"
OUT = HERE / "configs" / "onair_assets.h"

# name -> (symbol, mime). Order is fixed so the output is stable.
FILES = [
    ("onair.css", "ONAIR_CSS_GZ", "text/css"),
    ("onair.js", "ONAIR_JS_GZ", "text/javascript"),
]


def blob(symbol: str, raw: bytes) -> str:
    # mtime=0 so the same input always produces the same bytes - otherwise --check fails
    # every time it is run and the drift guard becomes noise people learn to ignore.
    packed = gzip.compress(raw, compresslevel=9, mtime=0)
    body = ",".join(str(b) for b in packed)
    return (
        f"// {len(raw)} bytes raw -> {len(packed)} gzipped\n"
        f"inline constexpr uint8_t {symbol}[{len(packed)}] = {{{body}}};\n"
    )


def render() -> str:
    out = [
        "#pragma once\n",
        "// GENERATED by firmware/tools/gen-assets.py from firmware/assets/. Do not edit.\n",
        "// Regenerate with `npm run firmware:assets`. `npm run verify` fails if this drifts.\n",
        "//\n",
        "// See D-69. These are served by AsyncWebServerResponseProgmem, which points at flash\n",
        "// and copies nothing into heap, with Content-Encoding: gzip and an immutable cache.\n",
        "\n#include <cstdint>\n\nnamespace onair {\n\n",
    ]
    for name, symbol, _mime in FILES:
        path = ASSETS / name
        if not path.exists():
            sys.exit(f"gen-assets: {path} is missing")
        out.append(blob(symbol, path.read_bytes()))
        out.append("\n")
    out.append("}  // namespace onair\n")
    return "".join(out)


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists():
            print(f"gen-assets: {OUT} does not exist - run `npm run firmware:assets`", file=sys.stderr)
            return 1
        if OUT.read_text() != text:
            print(
                f"gen-assets: {OUT} is stale - it does not match firmware/assets/.\n"
                f"            Run `npm run firmware:assets` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"gen-assets: {OUT.name} matches its sources")
        return 0
    OUT.write_text(text)
    total = sum(len((ASSETS / n).read_bytes()) for n, _, _ in FILES)
    packed = sum(len(gzip.compress((ASSETS / n).read_bytes(), 9, mtime=0)) for n, _, _ in FILES)
    print(f"gen-assets: wrote {OUT.name} - {total} bytes raw, {packed} gzipped")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
